<a href="https://colab.research.google.com/github/souzalh/dna_analysis/blob/main/analise_dna_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/souzalh/dna_analysis/refs/heads/main/synthetic_dna_dataset.csv')

In [5]:
df.head()

,Sample_ID,Sequence,GC_Content,AT_Content,Sequence_Length,Num_A,Num_T,Num_C,Num_G,kmer_3_freq,Mutation_Flag,Class_Label,Disease_Risk
0,SAMPLE_1,CTTTCGGGATACTTTTGGGATGGTCTTGGTCAAGGGTTTTAGCCCG...,50.0,50.0,100,22,28,19,31,0.986,0,Bacteria,High
1,SAMPLE_2,TTGACCAAATTTGATTGGAAGTGGTAAGCGCGTATTCCTAGCATCA...,45.0,55.0,100,27,28,22,23,0.486,1,Virus,Medium
2,SAMPLE_3,GCGTGAGTTCTAATTTAAAAAGTCGTAACACGTACCCCGGCGTGTA...,51.0,49.0,100,26,23,30,21,0.367,1,Bacteria,Low
3,SAMPLE_4,ACTACGCGGACAAGAACCAACAGAACCTGGTTTTCGCAAGGGAGTG...,55.0,45.0,100,28,17,23,32,0.404,0,Human,Medium
4,SAMPLE_5,TTCAATGCAGATTGAAAGTTACTTTCATCTGCCCTATGGGTCCCTT...,46.0,54.0,100,24,30,25,21,0.818,0,Human,High

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Sample_ID        3000 non-null   object
 1   Sequence         3000 non-null   object
 2   GC_Content       3000 non-null   float64
 3   AT_Content       3000 non-null   float64
 4   Sequence_Length  3000 non-null   int64
 5   Num_A            3000 non-null   int64
 6   Num_T            3000 non-null   int64
 7   Num_C            3000 non-null   int64
 8   Num_G            3000 non-null   int64
 9   kmer_3_freq      3000 non-null   float64
 10  Mutation_Flag    3000 non-null   int64
 11  Class_Label      3000 non-null   object
 12  Disease_Risk     3000 non-null   object
dtypes: float64(3), int64(6), object(4)
memory usage: 304.8+ KB

In [7]:
df.describe()

,GC_Content,AT_Content,Sequence_Length,Num_A,Num_T,Num_C,Num_G,kmer_3_freq,Mutation_Flag
count,3000.000000,3000.000000,3000.0,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,50.120000,49.880000,100.0,24.950667,24.929333,25.004000,25.116000,0.547738,0.496667
std,5.062688,5.062688,0.0,4.317458,4.317702,4.349056,4.329603,0.258521,0.500072
min,34.000000,34.000000,100.0,11.000000,9.000000,10.000000,12.000000,0.100000,0.000000
25%,47.000000,47.000000,100.0,22.000000,22.000000,22.000000,22.000000,0.330000,0.000000
50%,50.000000,50.000000,100.0,25.000000,25.000000,25.000000,25.000000,0.543000,0.000000
75%,53.000000,53.000000,100.0,28.000000,28.000000,28.000000,28.000000,0.772250,1.000000
max,66.000000,66.000000,100.0,40.000000,42.000000,42.000000,42.000000,1.000000,1.000000

In [8]:
df.shape

(3000, 13)

In [9]:
#Print das dimenções do DataFrame
linhas, colunas = df.shape[0], df.shape[1]
print(f'O DataFrame possuí {linhas} linhas e {colunas} colunas')

O DataFrame possuí 3000 linhas e 13 colunas

In [11]:
#Lista do nome das colunas
df.columns

Index(['Sample_ID', 'Sequence', 'GC_Content', 'AT_Content', 'Sequence_Length',
       'Num_A', 'Num_T', 'Num_C', 'Num_G', 'kmer_3_freq', 'Mutation_Flag',
       'Class_Label', 'Disease_Risk'],
      dtype='object')

In [12]:
df['Mutation_Flag'].value_counts()

Mutation_Flag
0    1510
1    1490
Name: count, dtype: int64

In [13]:
df['Class_Label'].value_counts()

Class_Label
Bacteria    761
Human       749
Plant       747
Virus       743
Name: count, dtype: int64

In [14]:
df['Disease_Risk'].value_counts()

Disease_Risk
High      1046
Low        978
Medium     976
Name: count, dtype: int64